### ISSUE TITLE
Stylelint extension complains about TSError

### ISSUE THREAD

**Issue by ZzzZeta** [hudochenkov/postcss-styled-syntax#8]
It throws errors for every character typing if the file is not yet a valid code. I think the ts parse error should not be thrown out.
```
TSError: Expression expected.     at createError (/workspaces/my-webapp/node_modules/postcss-styled-syntax/node_modules/@typescript-eslint/typescript-estree/dist/node-utils.js:529:12)     at convertError (/workspaces/my-webapp/node_modules/postcss-styled-syntax/node_modules/@typescript-eslint/typescript-estree/dist/convert.js:41:41)     at astConverter (/workspaces/my-webapp/node_modules/postcss-styled-syntax/node_modules/@typescript-eslint/typescript-estree/dist/ast-converter.js:15:42)     at parseWithNodeMapsInternal (/workspaces/my-webapp/node_modules/postcss-styled-syntax/node_modules/@typescript-eslint/typescript-estree/dist/parser.js:65:66)     at Object.parse (/workspaces/my-webapp/node_modules/postcss-styled-syntax/node_modules/@typescript-eslint/typescript-estree/dist/parser.js:43:21)     at parse (/workspaces/my-webapp/node_modules/postcss-styled-syntax/lib/parse.js:22:23)     at new LazyResult (/workspaces/my-webapp/node_modules/postcss/lib/lazy-result.js:133:16)     at getPostcssResult (/workspaces/my-webapp/node_modules/stylelint/lib/getPostcssResult.js:53:30)     at lintSource (/workspaces/my-webapp/node_modules/stylelint/lib/lintSource.js:99:10)     at async Function.standalone [as lint] (/workspaces/my-webapp/node_modules/stylelint/lib/standalone.js:122:26)
```

**Comment by hudochenkov** [comment]
Fixed in 0.3.3.
